import {StyleSheet} from 'react-native';

const style = StyleSheet.create({
  button1: {
    width: 190,
    height: 40,
    backgroundColor: 'transparent',
    color: '#638184',
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    borderRadius: 5,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: 9,
    borderWidth: 2,
    borderColor: '#638184',
    textAlign: 'center',
  },
  button2: {
    width: 190,
    height: 40,
    backgroundColor: 'transparent',
    color: '#638184',
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    borderRadius: 5,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: 9,
    borderWidth: 2,
    borderColor: '#638184',
    textAlign: 'center',
    top: -55,
  },
  button3: {
    width: 190,
    height: 40,
    backgroundColor: 'transparent',
    color: '#638184',
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    borderRadius: 5,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: 9,
    borderWidth: 2,
    borderColor: '#638184',
    textAlign: 'center',
  },
  textbox: {
    color: '#638184',
    borderColor: '#638184',
    borderBottomWidth: 2,
    paddingHorizontal: 0,
    width: 190,
    height: 22,
    fontSize: 14,
    fontFamily: 'Lexend-Regular',
    backgroundColor: 'transparent',
  },
  box1: {
    width: 190,
    height: 100,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    top: 130,
    marginLeft: 100,
  },
  box2: {
    width: 190,
    height: 220,
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 30,
    top: 90,
    marginLeft: 100,
  },
  box3 : {
    color: 'black',
    alignContent: 'left',
    justifyContent: 'left',
    gap: 8,
    top: -40,
  },
  box4: {
    width: 306,
    height: 350,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    top: 50,
    marginLeft: 45,
  },
  
  signInTitle : {
    color: '#DC989A',
    fontFamily: 'Poppins-Bold',
    //fontWeight: 'bold',
    fontSize: 51,
    alignItems: 'center',
    justifyContent: 'center',
    width: 190,
    height: 80,
    top: 100,
    marginLeft: 100,
  },
  registerTitle : {
    color: '#DC989A',
    fontFamily: 'Poppins-Bold',
    fontSize: 22,
    //fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    width: 190,
    height: 80,
    top: 10,
    marginLeft: 100,
  },
  signInText: {
    color: '#DC989A',
    textAlign: 'center',
    //fontWeight: 'bold',
    fontFamily: 'Lexend-Regular',
    top: 155,
    fontSize: 12,
    marginTop: 5,
  },
  userQues : {
    color: '#DC989A',
    textAlign: 'center',
    fontFamily: 'Lexend-Regular',
    top: -15,
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
    },
  numberInput : {
    backgroundColor: 'transparent',
    color: '#638184',
    borderColor: '#638184',
    borderBottomWidth: 5,
    paddingHorizontal: 0,
    textAlign: 'center',
    width: 190,
    height: 100,
    fontSize: 70,
    fontFamily: 'Lexend-Regular',
    backgroundColor: 'transparent',
  },
  userTitle : {
    color: '#DC989A',
    fontFamily: 'Poppins-Bold',
    fontSize: 32,
    //fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    width: 190,
    height: 50,
  },
  userTypeContainer : {
    flexDirection: 'row',
    alignItems: 'center',
    width: 170,
  },
  generalText : {
    color: '#638184',
    fontSize: 14,
    fontFamily: 'Lexend-Regular',
  },
  dashboard : {
    borderColor: '#EFD1D2',
    borderWidth: 5,
    justifyContent: 'center',
    alignContent: 'center',
    width: 190,
    borderRadius: 20,
    gap: 15,
    paddingBottom: 30,
    width: 330,
    alignItems: 'center',
    marginLeft: 30,
    top: 65
  },
  dashboardTitle : {
    backgroundColor: '#F4E5E6',
    color: '#DC989A',
    //fontWeight: 'bold',
    fontSize: 24,
    padding: 10,
    width: 320,
    textAlign: 'center',
    borderTopEndRadius: 15,
    fontFamily: 'Poppins-Regular',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  dashboardOptions : {
    color: '#638184',
    borderBottomWidth: 2,
    borderColor: '#638184',
    width: 200,
    fontSize: 18,
    paddingBottom: 15,
    fontFamily: 'Lexend-Regular',
  },
  generalBox : {
    borderColor: '#C2DCDE',
    borderWidth: 5,
    justifyContent: 'center',
    alignContent: 'center',
    width: 190,
    borderRadius: 20,
    gap: 7,
    paddingBottom: 30,
    width: 330,
    alignItems: 'center',
    marginLeft: 30,
    top: 30,
  },
  triggersTitle : {
    backgroundColor: '#D2E5E7',
    color: '#638184',
    fontSize: 25,
    padding: 10,
    width: 320,
    height: 55,
    textAlign: 'center',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    fontFamily: 'Poppins-Regular',
  },
  triggerOptions : {
    color: '638184',
    fontFamily: 'Lexend-Regular',
    fontSize: 16,
    color: '#638184',
  },
  dashboardContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 200,
  },
  checkboxContainer : {
    flexDirection: 'row',
    alignItems: 'center',
    width: 300,
  },
  keywords : {
    borderColor: '#C2DCDE',
    borderWidth: 5,
    justifyContent: 'center',
    alignContent: 'center',
    width: 190,
    borderRadius: 20,
    gap: 7,
    paddingBottom: 30,
    width: 330,
    alignItems: 'center',
    marginLeft: 30,
    top: 80,
  },
  radiobuttonContainer : {
    flexDirection: 'row',
    alignItems: 'center',
    width: 280,
  },
  reportButton: {
    width: 200,
    padding: 100,
  },
  timerContainer: {
    backgroundColor: "#F1F1F1", 
    alignItems: "center", 
    justifyContent: "center",
    top: 50,
  },
  QRContainer: {
    borderColor: '#C2DCDE',
    borderWidth: 5,
    justifyContent: 'center',
    alignContent: 'center',
    width: 190,
    borderRadius: 20,
    paddingBottom: 50,
    gap: 50,
    width: 330,
    alignItems: 'center',
    marginLeft: 30,
    top: 30,
  },
  doctorImage : {
    width: 50,
    height: 50,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: '#DC989A',
  },
  headerContainer : {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    justifyContent: 'center',
    backgroundColor: '#F2E1E2',
    padding: 20,
  },
  doctorTitle : {
    color: '#DC989A',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 24,
  },
  bgImage: {
    flex: 1,
    width:390,
    height:490,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: 100,
  },
  bgImage2: {
    flex: 1,
    width:306,
    height:550,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  bgImage3: {
    flex: 1,
    width:306,
    height:399,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: 120,
    margin: 40,
  },
  userCircle : {
    flex: 1,
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 30,
    marginTop: 20,
  },
  userGreet: {
    color: '#638184',
    fontFamily: 'Poppins-Bold',
    fontSize: 20,
    top: 20,
    marginLeft: 60,
  },
  userGreet2: {
    color: '#638184',
    fontFamily: 'Lexend-Regular',
    fontSize: 14,
    top: 17,
    marginLeft: 60,
  },
  bgGraphic1 : {
    flex: 1,
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 300,
  },
  bgGraphic2 : {
    flex: 1,
    width: 23,
    height: 23,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 280,
    top: 80,
  },
  bgGraphic3 : {
    flex: 1,
    width: 450,
    height: 700,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 0,
    top: 15,
  },
  bgGraphic4 : {
    flex: 1,
    width: 190,
    height: 190,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 205,
    top: 370,
  },
  bgGraphic5 : {
    flex: 1,
    width: 57,
    height: 57,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 18,
    top: 460,
  },
  bgGraphic6 : {
    flex: 1,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 85,
    top: 485,
  },
  bgGraphic7 : {
    flex: 1,
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 300,
    top: -60,
  },
  bgGraphic8 : {
    flex: 1,
    width: 23,
    height: 23,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 280,
    top: -75,
  },
  bgGraphic9 : {
    flex: 1,
    width: 150,
    height: 150,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 65,
    top: 520,
  },
  bgGraphic10 : {
    flex: 1,
    width: 23,
    height: 23,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: 43,
    top: 535,
  },
});

export default style;
