import {StyleSheet} from 'react-native';

const style = StyleSheet.create({
  button1: {
    width: 60.455,
    height: 30,
    backgroundColor: 'transparent',
    color: '#638184',
    fontFamily: 'Lexend',
    fontSize: 30,
    fontWeight: '400',
    borderRadius: 5,
    padding: 30,
    borderRadius: 5,
  },
  textbox: {
    color: '#638184',
    borderColor: '#638184',
    borderBottomWidth: 2,
    paddingHorizontal: 0,
    width: 190,
    height: 22,
    fontSize: 14,
    fontFamily: 'Lexend',
    backgroundColor: 'transparent',
  },
  box1: {
    width: 190,
    height: 100,
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 10,
    top: 240,
    marginLeft: 100,
  },
  box2: {
    width: 190,
    height: 220,
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 10,
    top: 140,
    marginLeft: 100,
  },
  box3 : {
    color: 'black',
    alignContent: 'left',
    justifyContent: 'left',
    gap: 3,
  },
  signInTitle : {
    color: '#DC989A',
    fontFamily: 'Poppins-Regular',
    fontWeight: 'bold',
    fontSize: 61,
    alignItems: 'center',
    justifyContent: 'center',
    width: 190,
    height: 80,
    top: 180,
    marginLeft: 100,
  },
  registerTitle : {
    color: '#DC989A',
    fontFamily: 'Poppins-Regular',
    fontSize: 27,
    fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    width: 190,
    height: 80,
    top: 120,
    marginLeft: 100,
  },
  signInText: {
    color: '#DC989A',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
    },
  numberInput : {
    backgroundColor: 'transparent',
    borderColor: '#638184',
    borderBottomWidth: 5,
    paddingHorizontal: 0,
    textAlign: 'center',
    width: 190,
    height: 100,
    fontSize: 70,
    fontFamily: 'Lexend',
    backgroundColor: 'transparent',
  },
  userTitle : {
    color: '#DC989A',
    fontFamily: 'Poppins-Regular',
    fontSize: 38,
    fontWeight: 'bold',
    alignItems: 'center',
    justifyContent: 'center',
    width: 190,
    height: 50,
  },
  generalText : {
    color: '#638184',
    fontSize: 14,
  },
  dashboard : {
    borderColor: '#EFD1D2',
    borderWidth: 5,
    justifyContent: 'center',
    alignContent: 'center',
    width: 190,
    borderRadius: 20,
    gap: 15,
    paddingBottom: 30,
    width: 330,
    alignItems: 'center',
    marginLeft: 30,
    top: 100,
  },
  dashboardTitle : {
    backgroundColor: '#EFD1D2',
    color: '#DC989A',
    fontWeight: 'bold',
    fontSize: 35,
    padding: 10,
    width: 320,
    textAlign: 'center',
    borderTopEndRadius: 15,
  },
  dashboardOptions : {
    color: '#638184',
    borderBottomWidth: 2,
    borderColor: '#638184',
    width: 230,
    fontSize: 18,
    paddingBottom: 10,
  },
});

export default style;
